In [11]:
import pandas as pd

In [12]:
df=pd.read_csv("recipes.csv")
df.head(2)
df[df['cookTimeMinutes']<15]

,Unnamed: 0,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,reviewCount
2,2,Chocolate Chip Cookies,15,10,24,150,13
6,6,Tomato Basil Bruschetta,15,10,6,120,95
8,8,Caprese Salad,10,0,2,200,82
21,21,Mango Lassi,10,0,2,180,15
22,22,Italian Tiramisu,30,0,6,350,0
24,24,Blueberry Banana Smoothie,10,0,1,220,30
28,28,Lebanese Falafel Wrap,15,10,2,400,84
29,29,Brazilian Caipirinha,5,0,1,150,55

In [15]:
retete_noi={"name": ['tiramisu', "Gogosi"], "prepTimeMinutes":[25,20], "cookTimeMinutes":[90,40], 'servings': [12,40], 'caloriesPerServing':[500,600], "reviewCount":[3,5]}

In [16]:
df_noi=pd.DataFrame(retete_noi)
df_noi

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,reviewCount
0,tiramisu,25,90,12,500,3
1,Gogosi,20,40,40,600,5

In [ ]:
result_df=pd.merge(df,df_noi)
result_df.head()